services:
  db:
    image: postgres:15
    container_name: squid_postgres
    restart: always
    environment:
      POSTGRES_DB: usdctransfers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-5432}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    shm_size: 1gb
    networks:
      - squid-network

volumes:
  postgres-data:

networks:
  squid-network:
    external: true
